import { useCallback } from 'react';
import type { WhyBoardAnalysis } from '../types';

interface ExportButtonProps {
  analysis: WhyBoardAnalysis;
}

function formatExport(analysis: WhyBoardAnalysis): string {
  const { metadata } = analysis;
  const lines = [
    '═══════════════════════════════════════════',
    '  WhyBoard — Narrative Intelligence Report',
    '═══════════════════════════════════════════',
    '',
    '── EXECUTIVE SUMMARY ──',
    analysis.executive_narrative,
    '',
    '── ANALYST DEEP DIVE ──',
    analysis.analyst_narrative,
    '',
    '── KEY SIGNALS ──',
    ...analysis.key_signals.map(
      (s) => `  ${s.direction === 'up' ? '↑' : s.direction === 'down' ? '↓' : '→'} ${s.label}: ${s.value}`
    ),
    '',
    `⚠ RISK: ${analysis.risk_flag}`,
    `✦ OPPORTUNITY: ${analysis.opportunity_flag}`,
    '',
    '── METADATA ──',
    `  Data type: ${metadata.data_type}`,
    `  Dataset: ${metadata.row_count} rows × ${metadata.column_count} columns`,
    `  Data quality: ${metadata.data_quality_score}/100`,
    `  Response time: ${metadata.response_time_seconds}s`,
    `  Tokens used: ${metadata.token_usage.total_tokens.toLocaleString()} (in: ${metadata.token_usage.input_tokens.toLocaleString()}, out: ${metadata.token_usage.output_tokens.toLocaleString()})`,
    `  Cost: ₹${metadata.token_usage.cost_inr.toFixed(4)} ($${metadata.token_usage.cost_usd.toFixed(4)})`,
    `  Analyzed: ${new Date(metadata.analyzed_at).toLocaleString()}`,
    '',
    '── Generated by WhyBoard (ScriptsHub Internal) ──',
  ];
  return lines.join('\n');
}

function ExportButton({ analysis }: ExportButtonProps) {
  const handleExport = useCallback(() => {
    const content = formatExport(analysis);
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `whyboard-${analysis.metadata.data_type}-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [analysis]);

  return (
    <button
      onClick={handleExport}
      className="px-4 py-2 rounded-lg text-sm font-medium bg-gray-800 text-gray-400 hover:text-gray-200 border border-gray-700 hover:border-gray-500 transition-colors"
      title="Download as text file"
    >
      Export
    </button>
  );
}

export default ExportButton;
