import { useCallback } from 'react';
import type { WhyBoardAnalysis } from '../types';

interface ExportButtonProps {
  analysis: WhyBoardAnalysis;
}

function formatExport(analysis: WhyBoardAnalysis): string {
  const { metadata } = analysis;
  const lines = [
    'WhyBoard — Narrative Intelligence Report',
    '═'.repeat(42),
    '',
    'EXECUTIVE SUMMARY',
    '─'.repeat(42),
    analysis.executive_narrative,
    '',
    'ANALYST DEEP DIVE',
    '─'.repeat(42),
    analysis.analyst_narrative,
    '',
    'KEY SIGNALS',
    '─'.repeat(42),
    ...analysis.key_signals.map(
      (s) => `  ${s.direction === 'up' ? '\u2191' : s.direction === 'down' ? '\u2193' : '\u2192'} ${s.label}: ${s.value}`
    ),
    '',
    `RISK: ${analysis.risk_flag}`,
    `OPPORTUNITY: ${analysis.opportunity_flag}`,
    '',
    'METADATA',
    '─'.repeat(42),
    `  Data type:     ${metadata.data_type}`,
    `  Dataset:       ${metadata.row_count} rows \u00d7 ${metadata.column_count} columns`,
    `  Data quality:  ${metadata.data_quality_score}/100`,
    `  Response time: ${metadata.response_time_seconds}s`,
    `  Tokens:        ${metadata.token_usage.total_tokens.toLocaleString()} (in: ${metadata.token_usage.input_tokens.toLocaleString()}, out: ${metadata.token_usage.output_tokens.toLocaleString()})`,
    `  Cost:          \u20B9${metadata.token_usage.cost_inr.toFixed(4)} ($${metadata.token_usage.cost_usd.toFixed(4)})`,
    `  Analyzed:      ${new Date(metadata.analyzed_at).toLocaleString()}`,
    '',
    'Generated by WhyBoard — ScriptsHub Internal',
  ];
  return lines.join('\n');
}

function ExportButton({ analysis }: ExportButtonProps) {
  const handleExport = useCallback(() => {
    const content = formatExport(analysis);
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `whyboard-${analysis.metadata.data_type}-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [analysis]);

  return (
    <button
      onClick={handleExport}
      className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium bg-surface-1 text-gray-400 hover:text-gray-200 border border-surface-3/50 hover:border-surface-3 transition-all"
      title="Download as text file"
    >
      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
      </svg>
      Export
    </button>
  );
}

export default ExportButton;
